### ISSUE TITLE
Wants To Add A Good Welcome Page

### ISSUE THREAD

**Issue by Harshith1263** [droy312/hacktoberfest_2022_flutter_opensource_project#44]
Sir Actually, I Want To Add A Welcome Page For You As Page-0 Using Neon Effects. Like

                                                                                             Dhritiman Roy
                                                                                     Welcome Poster(Neon)
                                                                                                     You

**Comment by Harshith1263** [comment]
My Whole It Is To Create A Welcome Page For You Sir !!

**Comment by IIdroyII** [comment]
Ok great. Assigning the issue to you. Please don't mention my name neither my initials.

**Comment by Harshith1263** [comment]
Ok, Sir Sure !!
